name: renewable_power_plants

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - bokeh==0.12.2
  - notebook  # jupyter notebook
  - numpy=1.11.1
  - pandas=0.18.1
  - pyyaml=3.12
  - requests
  - sqlalchemy
  - xlrd
  - xlsxwriter
  - pip:
    - utm==0.4.1
    - geocoder==1.38.1
